#!/usr/bin/env bash
# Frontend build script for Render Static Site
# Render injects BACKEND_URL as an environment variable
# This script creates a runtime config that replaces localhost with the real backend URL

set -e

BACKEND=${BACKEND_URL:-http://localhost:8000}

echo "Building frontend with BACKEND_URL = $BACKEND"

# Create runtime config.js with the actual backend URL baked in
cat > config.js << JSEOF
// Auto-generated by build.sh — do not edit manually
window.__BACKEND_URL__ = '${BACKEND}';
const BACKEND_URL = '${BACKEND}';
JSEOF

echo "config.js generated:"
cat config.js
echo "Frontend build complete."
